server {
    # This internal Nginx serves only frontend static files
    listen 80;
    server_name localhost;

    location / {
        # Path where the frontend Dockerfile copies the built React code
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # SPA configuration for React Router:
        # If the requested file is not found, Nginx serves index.html,
        # allowing React Router to handle routing internally.
        try_files $uri $uri/ /index.html;
    }

    # Serve a fallback page for server-side errors
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
